[platformio]
default_envs = t-watch-s3-pdm-monitor
boards_dir = ../../boards

[env:t-watch-s3-pdm-monitor]
platform = espressif32@6.11.0
board = t-watch-s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_16MB.csv
board_build.variants_dir = ../../variants

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=0
  -DARDUINO_RUNNING_CORE=1
  -DARDUINO_EVENT_RUNNING_CORE=1
